version: '3.1'

services:

  client:
    build:
      context: client/.
    command: echo 'client ready'
    volumes: 
      - $PWD/client:/opt/app:delegated
      - notused:/opt/app/node_modules

  server:
    build: 
      context: server/.
      args:
        - NODE_ENV=development
    command: nodemon --inspect index.js 0.0.0.0:9229
    ports:
      - "80:80"
      - "5858:5858"
      - "9229:9229"
    volumes: 
      - $PWD/server:/opt/app:delegated
      - notused:/opt/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  notused: